# Generated by Django 4.2.1 on 2023-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_vacancy_favorites'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberabstractuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='work.vacancy'),
        ),
    ]
