# Generated by Django 4.2.1 on 2023-05-07 17:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_phonetoken_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128, region=None),
        ),
    ]
