# Generated by Django 4.2.1 on 2023-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_phonetoken_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetoken',
            name='test',
            field=models.CharField(default='', max_length=23),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='otp',
            field=models.CharField(editable=False, max_length=42),
        ),
    ]
