# Generated by Django 4.2.1 on 2023-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_phonetoken_test_alter_phonetoken_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetoken',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
    ]
