# Generated by Django 4.2.1 on 2023-08-01 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250)),
                ('specialty', models.CharField(blank=True, choices=[('LO', 'Logistika'), ('CR', 'Kuryer'), ('PR', 'Dasturchi'), ('DV', 'Haydovchi'), ('DR', 'Direktor'), ('SM', 'Sotuvchi'), ('SU', 'Nazoratchi'), ('SE', 'Tikuvchi'), ('MR', 'Menejer'), ('CI', 'Kassir'), ('EG', 'Muhandis'), ('WA', 'Ofisiant'), ('OR', 'Operator'), ('AD', 'Administrator'), ('CL', 'Tozalovchi'), ('LW', 'Huquqshunos'), ('AS', 'Yordamchi'), ('BU', 'Quruvchi'), ('AM', 'Boshqaruvchi yordamchisi'), ('DE', 'Dizayner'), ('WD', 'Payvandchi'), ('AC', 'Buxgalter'), ('SK', "Do'kondor"), ('SC', 'Secretary'), ('LD', 'Yuklovchi'), ('EL', 'Elektrchi'), ('CO', 'Oshpaz'), ('EC', 'Iqtisodchi'), ('ME', 'Merchandiser'), ('SA', 'Tizim Administratori'), ('TO', 'Turist')], max_length=2)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('currency', models.CharField(choices=[('do', '$'), ('sm', 'сум')], default='sm', max_length=2)),
                ('from_salary', models.DecimalField(decimal_places=0, default=0, max_digits=50)),
                ('to_salary', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=50)),
                ('bargain', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('tg_contact', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='work_vacanc_title_86e612_idx')],
            },
        ),
    ]
