# Generated by Django 4.2.1 on 2023-08-01 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
