# Generated by Django 4.2.1 on 2023-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_vacancy_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='from_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='to_salary',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
